// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfbF5JElQoAbXe8qud3rQM38M4XEP8mh8',
    appId: '1:106972359177:web:983342cec8b970522126d8',
    messagingSenderId: '106972359177',
    projectId: 'flutterlab-dev',
    authDomain: 'flutterlab-dev.firebaseapp.com',
    storageBucket: 'flutterlab-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAAdD5cOxbVVe4mbSgiJyH3sBQnUIZ2xs',
    appId: '1:106972359177:android:ba225cba0d7880712126d8',
    messagingSenderId: '106972359177',
    projectId: 'flutterlab-dev',
    storageBucket: 'flutterlab-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApaSwmW9p9BSwB6GAd8Eeh9hcsWO9AkWw',
    appId: '1:106972359177:ios:47b42be1c8b7ee362126d8',
    messagingSenderId: '106972359177',
    projectId: 'flutterlab-dev',
    storageBucket: 'flutterlab-dev.firebasestorage.app',
    iosBundleId: 'com.example.flutterlab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApaSwmW9p9BSwB6GAd8Eeh9hcsWO9AkWw',
    appId: '1:106972359177:ios:47b42be1c8b7ee362126d8',
    messagingSenderId: '106972359177',
    projectId: 'flutterlab-dev',
    storageBucket: 'flutterlab-dev.firebasestorage.app',
    iosBundleId: 'com.example.flutterlab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfbF5JElQoAbXe8qud3rQM38M4XEP8mh8',
    appId: '1:106972359177:web:c129380c5ff811e22126d8',
    messagingSenderId: '106972359177',
    projectId: 'flutterlab-dev',
    authDomain: 'flutterlab-dev.firebaseapp.com',
    storageBucket: 'flutterlab-dev.firebasestorage.app',
  );
}
