import '../../models/product.dart';

final List<Product> mockProducts = [
  Product(
    id: '1',
    name: 'Apple Watch',
    category: 'Eletrônicos',
    price: 1200,
    quantity: 3,
    active: true,
    createdAt: DateTime.now().subtract(const Duration(days: 1)),
  ),
  Product(
    id: '2',
    name: 'AirPods',
    category: 'Eletrônicos',
    price: 900,
    quantity: 5,
    active: true,
    createdAt: DateTime.now().subtract(const Duration(days: 3)),
  ),
  Product(
    id: '2',
    name: 'AirPods',
    category: 'Eletrônicos',
    price: 900,
    quantity: 5,
    active: true,
    createdAt: DateTime.now().subtract(const Duration(days: 3)),
  ),
  Product(
    id: '3',
    name: 'Agenda',
    category: 'Papelaria',
    price: 40,
    quantity: 10,
    active: false,
    createdAt: DateTime.now().subtract(const Duration(days: 10)),
  ),
  Product(
    id: '4',
    name: 'Planner',
    category: 'Papelaria',
    price: 50,
    quantity: 15,
    active: true,
    createdAt: DateTime.now().subtract(const Duration(days: 10)),
  ),
  Product(
    id: '5',
    name: 'Canetas',
    category: 'Papelaria',
    price: 4,
    quantity: 40,
    active: false,
    createdAt: DateTime.now().subtract(const Duration(days: 10)),
  ),
  Product(
    id: '6',
    name: 'Tablet',
    category: 'Eletrônicos',
    price: 480,
    quantity: 10,
    active: true,
    createdAt: DateTime.now().subtract(const Duration(days: 10)),
  ),
  Product(
    id: '6',
    name: 'Tablet',
    category: 'Eletrônicos',
    price: 480,
    quantity: 10,
    active: true,
    createdAt: DateTime.now().subtract(const Duration(days: 10)),
  ),
];
